//! Build script.
//!
//! Besides Tauri's own setup, this walks `converter-scripts/models` and writes
//! the list of built-in converters into `OUT_DIR`, so a converter directory is
//! the whole of what shipping one takes: the document and the script it names
//! are embedded from exactly where they sit. A directory that is not a
//! well-formed converter is a defect in this build rather than in anything a
//! reader can fix, so it stops the build here.

use std::fs;
use std::path::{Path, PathBuf};

/// Where the built-in converters live, relative to this crate.
const MODELS_ROOT: &str = "converter-scripts/models";

fn main() {
    emit_builtin_scripts();
    tauri_build::build();
}

/// Writes `builtin_scripts.rs` beside the other build output.
fn emit_builtin_scripts() {
    let root = Path::new(MODELS_ROOT);
    println!("cargo:rerun-if-changed={MODELS_ROOT}");

    let mut entries = String::new();
    for capability in directories(root) {
        for converter in directories(&capability) {
            entries.push_str(&converter_definition(&capability, &converter));
        }
    }
    assert!(
        !entries.is_empty(),
        "{MODELS_ROOT} holds no converter, which is a defect in this build"
    );

    let mut source = String::from(
        "// The built-in converters, generated by `build.rs` from the converter\n\
         // directories this crate ships. Do not edit: add a directory under\n\
         // converter-scripts/models instead. The paths below are absolute, so\n\
         // the embeddings resolve from wherever the build output is written.\n\
         pub const BUILTIN_SCRIPTS: &[ScriptDef] = &[\n",
    );
    source.push_str(&entries);
    source.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("builtin_scripts.rs");
    fs::write(&out, source).unwrap_or_else(|e| panic!("cannot write {}: {e}", out.display()));
}

/// One `ScriptDef` per converter directory, with both files embedded from
/// where they sit.
fn converter_definition(capability: &Path, converter: &Path) -> String {
    let document = converter.join("model.json");
    let text = fs::read_to_string(&document)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", document.display()));
    let script = script_beside(&text, &document);
    let script_path = converter.join(&script);
    assert!(
        script_path.is_file(),
        "{}: the document names '{script}', which is not beside it",
        document.display()
    );
    println!("cargo:rerun-if-changed={}", document.display());
    println!("cargo:rerun-if-changed={}", script_path.display());

    let capability = name_of(capability);
    let id = name_of(converter);
    let document = absolute(&document);
    let script_path = absolute(&script_path);
    format!(
        "    ScriptDef {{\n\
         \x20       capability: {capability:?},\n\
         \x20       id: {id:?},\n\
         \x20       config: include_str!({document:?}),\n\
         \x20       script: include_str!({script:?}),\n\
         \x20   }},\n",
        document = document.display().to_string(),
        script = script_path.display().to_string(),
    )
}

/// The same path as an absolute one: `include_str!` in the generated file
/// resolves relative to the output directory it is written to, so nothing
/// relative would survive the trip.
fn absolute(path: &Path) -> PathBuf {
    fs::canonicalize(path).unwrap_or_else(|e| panic!("cannot resolve {}: {e}", path.display()))
}

/// The `script` a document names, which has to be a bare filename beside it —
/// the same rule the registry applies at runtime, applied here so a converter
/// that would be refused at load time stops the build instead.
fn script_beside(text: &str, document: &Path) -> String {
    let parsed: serde_json::Value = serde_json::from_str(text)
        .unwrap_or_else(|e| panic!("{} does not parse: {e}", document.display()));
    let script = parsed
        .get("script")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_else(|| panic!("{} names no script", document.display()));
    let bare = Path::new(script).file_name() == Some(std::ffi::OsStr::new(script));
    assert!(
        bare && !script.is_empty() && script != "model.json",
        "{}: script '{script}' is not a filename beside the document",
        document.display()
    );
    script.to_string()
}

/// The subdirectories of `dir`, by name, ignoring everything else. A directory
/// that does not exist reads as none.
fn directories(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut found: Vec<PathBuf> = entries
        .flatten()
        .filter(|entry| entry.file_type().map(|kind| kind.is_dir()).unwrap_or(false))
        .map(|entry| entry.path())
        .collect();
    found.sort();
    found
}

/// The last segment of a path, which is what a converter is keyed by.
fn name_of(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_else(|| panic!("{} has no usable name", path.display()))
        .to_string()
}
