import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import type {
  AssetId,
  AssetProvenance,
  ResourceEntry,
} from "../../../shared/domain";
import {
  ASSET_CATEGORY_LABELS,
  ASSET_KIND_LABELS,
} from "../../../shared/domain";
import { assetUrl } from "../../../api";
import { i18n } from "../../../shared/i18n";
import {
  buildIssueIndex,
  formatBytes,
  formatDuration,
} from "../canvas/mediaCards";
import { useEditorStore } from "../stores/editorStore";
import { useProjectStore } from "../stores/projectStore";
import { BAR_ENTRIES, TOOL_LABELS } from "../stores/toolPrefs";
import { shelfOf } from "./canvasAssets";
import { SHELF_WHERE_LABELS, kindOfShelf, shelfWhere } from "./shelfFilter";

/**
 * What a file is, told once for every column that reads one.
 *
 * The canvas's inspector reads a file a card holds and a reader asked the
 * shelf about, and the files room reads any file the project holds; the same
 * file must read the same in both, so the rows, the preview and the answers
 * about where it came from live here rather than once per column. What a page
 * adds — the board's card count, the room's uses list — arrives as what
 * surrounds these sections, never as a second telling of the file itself.
 */

/** One labelled fact about a file. Nothing said, nothing shown. */
export function Row({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <div className="inspector-row">
      <span>{label}</span>
      <span title={value}>{value}</span>
    </div>
  );
}

export function AssetRows({ entry }: { entry: ResourceEntry }) {
  const { t } = useTranslation();
  const probe = entry.probe;
  const dimensions =
    probe?.width && probe.height ? `${probe.width}×${probe.height}` : "";
  const audio = probe?.sampleRate
    ? `${Math.round(probe.sampleRate / 100) / 10} kHz · ${probe.channels ?? "?"} ch`
    : "";
  return (
    <>
      <Row label={t("editor:field.file")} value={entry.name} />
      <Row
        label={t("editor:field.type")}
        value={entry.mime ?? probe?.mime ?? ""}
      />
      <Row label={t("editor:field.dimensions")} value={dimensions} />
      <Row
        label={t("editor:field.duration")}
        value={formatDuration(probe?.durationMs)}
      />
      <Row label={t("editor:field.audio")} value={audio} />
      <Row label={t("editor:field.codec")} value={probe?.codecSummary ?? ""} />
      <Row
        label={t("editor:field.size")}
        value={formatBytes(entry.bytes ?? probe?.bytes)}
      />
      <Row label={t("editor:field.path")} value={entry.path} />
    </>
  );
}

/**
 * Which of the tools on the bar made this, in the word the bar uses.
 *
 * A tool records itself in the snapshot it leaves behind, and what it records is
 * the name it answers to on the server. Only a name the bar also offers is read
 * as a tool: anything else is a snapshot from somewhere else, and guessing at it
 * would say something the picture did not do.
 */
function toolThatMade(provenance: AssetProvenance): string | null {
  const named = provenance.parameterSnapshot?.tool;
  if (typeof named !== "string") return null;
  const entry = BAR_ENTRIES.find((candidate) => candidate === named);
  return entry === undefined ? null : i18n.t(TOOL_LABELS[entry]);
}

/** The picture a tool worked on, by name when the project still holds it. */
function workedOn(
  provenance: AssetProvenance,
  resources: ReadonlyMap<AssetId, ResourceEntry>,
): string {
  const recorded = provenance.parameterSnapshot?.sourceAssetId;
  const subject =
    provenance.inputAssetIds?.[0] ??
    (typeof recorded === "string" ? recorded : undefined);
  if (!subject) return "";
  return resources.get(subject)?.name ?? subject;
}

/**
 * Where a picture came from.
 *
 * Two things make one here and they leave different marks. A tool worked the
 * pixels of a picture already in the project, so what it has to say is which tool
 * and which picture, and there is no run behind it; an answer from a model has a
 * run and a node that asked for it. Calling a crop "generated by workflow" points
 * at a run that never happened, and rows left empty are questions left hanging.
 */
export function ProvenanceRows({
  entry,
  resources,
}: {
  entry: ResourceEntry;
  resources: ReadonlyMap<AssetId, ResourceEntry>;
}) {
  const { t } = useTranslation();
  const provenance = entry.provenance;
  if (!provenance) return null;
  const tool = toolThatMade(provenance);
  return (
    <>
      <h3>{t("editor:field.provenance")}</h3>
      {tool ? (
        <>
          <Row label={t("editor:field.madeBy")} value={tool} />
          <Row
            label={t("editor:field.from")}
            value={workedOn(provenance, resources)}
          />
        </>
      ) : (
        <>
          <Row
            label={t("editor:field.source")}
            value={t("editor:inspector.generatedByWorkflow")}
          />
          <Row label={t("editor:field.run")} value={provenance.runId ?? ""} />
          <Row
            label={t("editor:field.operationNode")}
            value={provenance.operationNodeId ?? ""}
          />
        </>
      )}
      <Row
        label={t("editor:field.created")}
        value={formatStamp(provenance.createdAt)}
      />
    </>
  );
}

/** When a file arrived or was last written, as this machine says it. */
function formatStamp(iso?: string): string {
  if (!iso) return "";
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? "" : date.toLocaleString();
}

/**
 * The words a text file holds.
 *
 * Read out of the file rather than out of its entry: an entry says what a file
 * is about in a word or two, and a reader who clicked a text file to see what
 * is in it is asking the file. Cut short, since the column beside the canvas is
 * no place to read a long thing — the whole of it is a download away.
 */
export function TextExcerpt({ entry }: { entry: ResourceEntry }) {
  const { t } = useTranslation();
  const [text, setText] = useState<string | null>(null);
  const [failure, setFailure] = useState<string | null>(null);

  useEffect(() => {
    let wanted = true;
    setText(null);
    setFailure(null);
    fetch(assetUrl(entry.id))
      .then((response) =>
        response.ok
          ? response.text()
          : Promise.reject(
              new Error(`${response.status} ${response.statusText}`.trim()),
            ),
      )
      .then((body) => {
        if (wanted) setText(body.slice(0, 600));
      })
      .catch((problem: unknown) => {
        // What the read answered, kept: "could not be read" says what happened
        // and not why, and the status is the half a reader can act on.
        if (wanted) {
          setFailure(
            problem instanceof Error ? problem.message : String(problem),
          );
        }
      });
    return () => {
      wanted = false;
    };
  }, [entry.id]);

  if (failure !== null) {
    return (
      <p className="inspector-empty" data-testid="asset-text-failed">
        {t("editor:inspector.textUnreadable")}
        <br />
        <span className="error-state-reason">{failure}</span>
      </p>
    );
  }
  if (text === null) {
    return <p className="inspector-empty">{t("editor:inspector.reading")}</p>;
  }
  return (
    <p className="inspector-text-excerpt" data-testid="asset-text">
      {text.trim() ? text : t("editor:inspector.empty")}
    </p>
  );
}

/**
 * What a file looks like, when it is the kind of file that looks like anything.
 *
 * Drawn from the file itself rather than from a card that holds it, since what
 * is being read here is the file the project holds — the same bytes whichever
 * board it was dragged onto, and readable when no board holds it at all.
 */
export function AssetPreview({
  entry,
  mime,
}: {
  entry: ResourceEntry;
  mime: string;
}) {
  const { t } = useTranslation();
  const openPreview = useEditorStore((state) => state.openPreview);
  const url = assetUrl(entry.id);
  if (mime.startsWith("image/")) {
    return (
      <button
        aria-label={t("editor:inspector.openFullPreview")}
        className="inspector-preview"
        data-testid="asset-preview-image"
        onClick={() => openPreview(entry.id)}
        type="button"
      >
        <img alt={entry.name} src={url} />
      </button>
    );
  }
  if (mime.startsWith("video/")) {
    return (
      <video
        controls
        data-testid="asset-preview-video"
        preload="metadata"
        src={url}
      />
    );
  }
  if (mime.startsWith("audio/")) {
    return (
      <audio
        controls
        data-testid="asset-preview-audio"
        preload="metadata"
        src={url}
      />
    );
  }
  if (mime.startsWith("text/")) return <TextExcerpt entry={entry} />;
  return (
    <p className="inspector-empty" data-testid="asset-preview-none">
      {mime
        ? t("editor:inspector.nothingToShowForMime", { mime })
        : t("editor:inspector.nothingToShow")}
    </p>
  );
}

/** What the project's last reading of itself says is wrong with this file. */
function useAssetIssue(assetId: AssetId) {
  const selfCheck = useProjectStore((state) => state.selfCheck);
  return buildIssueIndex(selfCheck).get(assetId);
}

/**
 * What the file looks like, with the reading that says there is nothing to
 * look at: a file missing from disk, changed under the project or empty is
 * told as that rather than drawn from bytes that are gone or no longer it.
 */
export function AssetPreviewSection({ entry }: { entry: ResourceEntry }) {
  const { t } = useTranslation();
  const issue = useAssetIssue(entry.id);
  const mime = entry.mime ?? entry.probe?.mime ?? "";
  return (
    <section className="inspector-section">
      <h3>{t("editor:field.preview")}</h3>
      {issue && (
        <p className="inspector-media-broken" role="alert">
          {t("editor:inspector.assetBroken", {
            state: t(
              issue === "missing"
                ? "editor:inspector.mediaStateMissing"
                : issue === "changed"
                  ? "editor:inspector.mediaStateChanged"
                  : "editor:inspector.mediaStateEmpty",
            ),
          })}
          {issue === "changed"
            ? t("editor:inspector.contentsChangedOnDisk")
            : ""}
        </p>
      )}
      {!issue && <AssetPreview entry={entry} mime={mime} />}
    </section>
  );
}

/** What the project files this file as, and what was said about it. */
export function AssetFileSection({ entry }: { entry: ResourceEntry }) {
  const { t } = useTranslation();
  const shelf = shelfOf(entry);
  const keeper = entry.favorite === true;
  return (
    <section className="inspector-section">
      <h3>{t("editor:field.file")}</h3>
      <Row
        label={t("editor:field.shelf")}
        value={
          shelf
            ? `${t(ASSET_CATEGORY_LABELS[shelf])} · ${t(ASSET_KIND_LABELS[kindOfShelf(shelf)])}`
            : ""
        }
      />
      <AssetRows entry={entry} />
      <Row
        label={t("editor:field.origin")}
        value={t(SHELF_WHERE_LABELS[shelfWhere(entry)])}
      />
      <Row
        label={t("editor:field.keptToHand")}
        value={keeper ? t("editor:field.yes") : ""}
      />
      <Row
        label={t("editor:field.words")}
        value={(entry.tags ?? []).join(", ")}
      />
      <Row label={t("editor:field.about")} value={entry.keyword ?? ""} />
      <Row
        label={t("editor:field.added")}
        value={formatStamp(entry.createdAt)}
      />
      <Row
        label={t("editor:field.updated")}
        value={formatStamp(entry.updatedAt)}
      />
    </section>
  );
}

/** What a reader noted about the file, in their own words. */
export function AssetNoteSection({ entry }: { entry: ResourceEntry }) {
  const { t } = useTranslation();
  if (!entry.note) return null;
  return (
    <section className="inspector-section">
      <h3>{t("editor:field.note")}</h3>
      <p className="inspector-text-excerpt">{entry.note}</p>
    </section>
  );
}

/**
 * Where the file came from, with the card that made it as a way across when
 * the page has somewhere to go: the board a generation node sits on is the
 * board the room opens, and the column beside the canvas has no such way to
 * offer — a card's own maker is already in front of the reader there.
 */
export function AssetProvenanceSection({
  entry,
  resources,
  onOpenMaker,
  makerLabel,
}: {
  entry: ResourceEntry;
  resources: ReadonlyMap<AssetId, ResourceEntry>;
  onOpenMaker?: (provenance: AssetProvenance) => void;
  makerLabel?: string;
}) {
  const provenance = entry.provenance;
  if (!provenance) return null;
  const maker = onOpenMaker && provenance.operationNodeId ? onOpenMaker : null;
  return (
    <section className="inspector-section">
      <ProvenanceRows entry={entry} resources={resources} />
      {maker && (
        <div className="inspector-actions">
          <button
            data-testid="asset-open-maker"
            onClick={() => maker(provenance)}
            type="button"
          >
            {makerLabel}
          </button>
        </div>
      )}
    </section>
  );
}
