import { useEffect, useMemo, useState } from "react";
import type {
  AssetId,
  CanvasDocument,
  GenerationSpec,
  ResourceEntry,
  ResultSlot,
  RunStatus,
  WorkflowEdge,
  WorkflowNode,
} from "../../../shared/domain";
import {
  CAPABILITY_LABELS,
  PROVIDER_EXECUTOR_KEY,
  executorKeyForNode,
  generationSpecFromSnapshot,
} from "../../../shared/domain";
import { assetsApi, assetUrl } from "../../../api";
import {
  GENERATION_UNAVAILABLE,
  useAppStore,
  useGenerationAvailable,
} from "../stores/appStore";
import { useEditorStore } from "../stores/editorStore";
import { useActiveCanvas, useProjectStore } from "../stores/projectStore";
import {
  retryRun,
  useLatestRunForNode,
  useNodeGenerationAssets,
  useNodeRunError,
  useNodeRunProgress,
  useNodeRuns,
  useNodeStreamText,
  useRunStore,
} from "../stores/runStore";
import {
  buildIssueIndex,
  buildResourceIndex,
  formatBytes,
  formatDuration,
  mediaInfoForNode,
} from "../canvas/mediaCards";
import {
  chooseResult,
  choosableResults,
  deleteSelection,
  disconnectEdge,
  renameNode,
  requestDeleteAsset,
  setNodeGeneration,
} from "../interactions/actions";

function Row({ label, value }: { label: string; value: string }) {
  if (!value) return null;
  return (
    <div className="inspector-row">
      <span>{label}</span>
      <span title={value}>{value}</span>
    </div>
  );
}

function TitleField({ node }: { node: WorkflowNode }) {
  const [value, setValue] = useState(node.title);
  useEffect(() => setValue(node.title), [node.id, node.title]);
  const commit = () => {
    const trimmed = value.trim();
    if (trimmed && trimmed !== node.title) {
      renameNode(node.id, trimmed);
    } else {
      setValue(node.title);
    }
  };
  return (
    <input
      aria-label="Node title"
      className="inspector-title-input"
      onBlur={commit}
      onChange={(event) => setValue(event.target.value)}
      onKeyDown={(event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          commit();
          event.currentTarget.blur();
        }
        if (event.key === "Escape") setValue(node.title);
      }}
      value={value}
    />
  );
}

/** Preview + metadata + provenance + file actions for a media node's asset. */
function MediaAssetSection({ node }: { node: WorkflowNode }) {
  const moka = useProjectStore((state) => state.moka);
  const selfCheck = useProjectStore((state) => state.selfCheck);
  const openPreview = useEditorStore((state) => state.openPreview);
  const media = useMemo(() => {
    if (!moka) return null;
    return mediaInfoForNode(
      node,
      buildResourceIndex(moka),
      buildIssueIndex(selfCheck),
    );
  }, [moka, selfCheck, node]);

  if (node.kind !== "image" && node.kind !== "audio" && node.kind !== "video") {
    return null;
  }
  const data = node.data as { assetId?: AssetId };
  if (!data.assetId) {
    return (
      <section className="inspector-section">
        <h3>Asset</h3>
        <p className="inspector-empty">No asset linked</p>
      </section>
    );
  }
  const entry = media?.entry;
  const broken = media && media.state !== "ready";

  const reveal = async (assetId: AssetId) => {
    try {
      await assetsApi.reveal(assetId);
    } catch (error) {
      useAppStore
        .getState()
        .pushToast(
          "error",
          error instanceof Error ? error.message : "Reveal failed",
        );
    }
  };

  return (
    <section className="inspector-section">
      <h3>Asset</h3>
      {broken && (
        <p className="inspector-media-broken" role="alert">
          ⚠ Asset {media.state}
          {media.state === "changed" ? " — file contents changed on disk" : ""}
        </p>
      )}
      {media?.state === "ready" && media.url && entry && (
        <>
          {node.kind === "image" && (
            <button
              aria-label="Open full preview"
              className="inspector-preview"
              onClick={() => openPreview(entry.id)}
              type="button"
            >
              <img alt={entry.name} src={media.url} />
            </button>
          )}
          {node.kind === "audio" && (
            <audio controls preload="metadata" src={media.url} />
          )}
          {node.kind === "video" && (
            <video controls preload="metadata" src={media.url} />
          )}
        </>
      )}
      {entry && <AssetRows entry={entry} />}
      {entry?.provenance && (
        <>
          <h3>Provenance</h3>
          <Row label="Source" value="Generated by workflow" />
          <Row label="Run" value={entry.provenance.runId ?? ""} />
          <Row
            label="Operation node"
            value={entry.provenance.operationNodeId ?? ""}
          />
          <Row label="Created" value={entry.provenance.createdAt} />
        </>
      )}
      {media?.state === "ready" && entry && (
        <div className="inspector-actions">
          <button onClick={() => void reveal(entry.id)} type="button">
            Reveal
          </button>
          <a download={entry.name} href={assetUrl(entry.id)}>
            Download
          </a>
          <button
            className="danger"
            onClick={() => void requestDeleteAsset(entry.id)}
            type="button"
          >
            Remove
          </button>
        </div>
      )}
    </section>
  );
}

function AssetRows({ entry }: { entry: ResourceEntry }) {
  const probe = entry.probe;
  const dimensions =
    probe?.width && probe.height ? `${probe.width}×${probe.height}` : "";
  const audio = probe?.sampleRate
    ? `${Math.round(probe.sampleRate / 100) / 10} kHz · ${probe.channels ?? "?"} ch`
    : "";
  return (
    <>
      <Row label="File" value={entry.name} />
      <Row label="Type" value={entry.mime ?? probe?.mime ?? ""} />
      <Row label="Dimensions" value={dimensions} />
      <Row label="Duration" value={formatDuration(probe?.durationMs)} />
      <Row label="Audio" value={audio} />
      <Row label="Codec" value={probe?.codecSummary ?? ""} />
      <Row label="Size" value={formatBytes(entry.bytes ?? probe?.bytes)} />
      <Row label="Path" value={entry.path} />
    </>
  );
}

/** Incoming-connection chips with disconnect / replace-via-pick actions. */
function InputChips({
  canvas,
  node,
}: {
  canvas: CanvasDocument;
  node: WorkflowNode;
}) {
  const inputPick = useEditorStore((state) => state.inputPick);
  const inputs = node.ports.filter((port) => port.direction === "input");
  if (inputs.length === 0 || node.kind === "group") return null;
  return (
    <section className="inspector-section">
      <h3>Inputs</h3>
      {inputs.map((port) => {
        const incoming = canvas.edges.filter(
          (edge) =>
            edge.target.nodeId === node.id && edge.target.portId === port.id,
        );
        const picking =
          inputPick?.nodeId === node.id && inputPick?.portId === port.id;
        return (
          <div className="inspector-input-port" key={port.id}>
            <div className="inspector-input-head">
              <span>
                {port.label}
                {port.required ? " *" : ""}
              </span>
              <button
                aria-pressed={picking}
                className={picking ? "is-active" : ""}
                onClick={() => {
                  const store = useEditorStore.getState();
                  if (picking) store.stopInputPick();
                  else
                    store.startInputPick({ nodeId: node.id, portId: port.id });
                }}
                type="button"
              >
                {picking ? "Cancel pick" : "Replace"}
              </button>
            </div>
            {picking && (
              <p className="inspector-pick-hint">
                Click a compatible source node on the canvas (Esc to cancel)
              </p>
            )}
            {incoming.length === 0 ? (
              <p className="inspector-empty">Not connected</p>
            ) : (
              <ul className="inspector-chip-list">
                {incoming.map((edge) => (
                  <InputChip canvas={canvas} edge={edge} key={edge.id} />
                ))}
              </ul>
            )}
          </div>
        );
      })}
    </section>
  );
}

function InputChip({
  canvas,
  edge,
}: {
  canvas: CanvasDocument;
  edge: WorkflowEdge;
}) {
  const source = canvas.nodes.find((node) => node.id === edge.source.nodeId);
  const portLabel = source?.ports.find(
    (port) => port.id === edge.source.portId,
  )?.label;
  const excerpt =
    source?.kind === "text"
      ? ((source.data as { content?: string }).content ?? "").slice(0, 24)
      : "";
  return (
    <li className="inspector-chip">
      <span className="inspector-chip-label">
        <strong>{source?.title ?? "Unknown"}</strong>
        {portLabel ? ` · ${portLabel}` : ""}
        {excerpt ? <em> “{excerpt}”</em> : null}
      </span>
      <button
        aria-label="Disconnect"
        onClick={() => disconnectEdge(edge.id)}
        type="button"
      >
        ✕
      </button>
    </li>
  );
}

const RUN_STATUS_LABEL: Record<RunStatus, string> = {
  queued: "Queued",
  running: "Running",
  succeeded: "Succeeded",
  failed: "Failed",
  cancelled: "Cancelled",
};

function formatTime(iso?: string): string {
  if (!iso) return "";
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? "" : date.toLocaleTimeString();
}

/** What a node asks a provider to make, as it stands now. */
function GenerationSection({ node }: { node: WorkflowNode }) {
  const spec = (node.data as { generation?: GenerationSpec }).generation;
  if (!spec) return null;
  return (
    <section className="inspector-section">
      <h3>Generation</h3>
      <Row label="Capability" value={CAPABILITY_LABELS[spec.capability]} />
      <Row label="Mode" value={spec.mode} />
      <Row label="Model" value={spec.model || "Provider default"} />
      <Row label="Inputs from" value={spec.inputMode} />
      <h3>Prompt</h3>
      <p className="inspector-text-excerpt">
        {spec.prompt.trim() ? spec.prompt : "Empty"}
      </p>
      {Object.keys(spec.params).length > 0 && (
        <pre className="inspector-json">
          {JSON.stringify(spec.params, null, 2)}
        </pre>
      )}
    </section>
  );
}

/**
 * What the last answer this node produced was asked for, and the way to ask for
 * it again.
 *
 * Taken from the assets rather than from a run record: an exported package
 * carries its assets and their provenance but no runs, so a control that needed
 * the run it came from would be dead in every document that arrived from
 * somewhere else. Asking again is therefore a new run under the snapshot's own
 * spec, and never a retry of a run that may not exist here to retry.
 */
function LastGeneration({
  canvas,
  node,
}: {
  canvas: CanvasDocument;
  node: WorkflowNode;
}) {
  const moka = useProjectStore((state) => state.moka);
  const made = useNodeGenerationAssets(node.id);
  const starting = useRunStore((state) => state.starting);
  const generationOn = useGenerationAvailable();
  const [busy, setBusy] = useState(false);
  const recorded = made
    .map((entry) => entry.provenance)
    .find((provenance) => provenance?.parameterSnapshot);
  const spec = generationSpecFromSnapshot(
    recorded?.parameterSnapshot,
    node.kind,
  );
  const inputs = useMemo(() => {
    const wanted = recorded?.inputAssetIds;
    if (!moka || !wanted) return "";
    const resources = buildResourceIndex(moka);
    return wanted.map((id) => resources.get(id)?.name ?? id).join(", ");
  }, [moka, recorded]);

  if (!recorded || !spec) return null;

  const askAgain = async () => {
    setBusy(true);
    try {
      // A run is served from the document on disk, so a spec this control has
      // to put back is saved before the run is asked for.
      setNodeGeneration(canvas.id, node.id, spec);
      await useProjectStore.getState().flush();
      await useRunStore.getState().start(canvas.id, [node.id]);
    } catch (error) {
      useAppStore
        .getState()
        .pushToast(
          "error",
          error instanceof Error ? error.message : "Run failed to start",
        );
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <h3>Last generation</h3>
      <Row label="Inputs" value={inputs} />
      <pre className="inspector-json">
        {JSON.stringify(recorded.parameterSnapshot, null, 2)}
      </pre>
      <div className="inspector-actions">
        <button
          aria-label="Run again with the parameters of the last generation"
          disabled={busy || starting || !generationOn}
          onClick={() => void askAgain()}
          title={generationOn ? undefined : GENERATION_UNAVAILABLE}
          type="button"
        >
          {busy ? "Starting…" : "Run again"}
        </button>
      </div>
    </>
  );
}

/** Run controls, latest run state, and result slots for the selected node. */
function RunSection({
  canvas,
  node,
}: {
  canvas: CanvasDocument;
  node: WorkflowNode;
}) {
  const run = useLatestRunForNode(node.id);
  const asked = useNodeRuns(node.id);
  const choices = choosableResults(canvas, node);
  const starting = useRunStore((state) => state.starting);
  const issues = useRunStore((state) => state.lastIssues);
  const generationOn = useGenerationAvailable();
  const progress = useNodeRunProgress(node.id);
  const failure = useNodeRunError(node.id);
  const active = run?.status === "queued" || run?.status === "running";
  const said = useNodeStreamText(node.id);
  const step = run?.steps.find((entry) => entry.nodeId === node.id);
  const slots = (node.data as { resultSlots?: ResultSlot[] }).resultSlots ?? [];
  const relevantIssues = issues.filter(
    (issue) => !issue.nodeId || issue.nodeId === node.id,
  );
  // Which executor a step would go to, rather than which kind of node this is:
  // a generation node is as runnable as an operation one, and a node neither
  // executor would take has no business offering a control at all.
  const executor = executorKeyForNode(node);
  const offline = executor === PROVIDER_EXECUTOR_KEY && !generationOn;
  const retryable = run?.status === "failed" || run?.status === "cancelled";

  const start = async () => {
    try {
      await useRunStore.getState().start(canvas.id, [node.id]);
    } catch {
      // Issues surface below via lastIssues; transport errors toast globally.
    }
  };

  return (
    <section className="inspector-section">
      <h3>Run</h3>
      {executor !== null && (
        <div className="inspector-actions">
          <button
            disabled={starting || offline}
            onClick={() => void start()}
            title={offline ? GENERATION_UNAVAILABLE : undefined}
            type="button"
          >
            {starting ? "Starting…" : "▶ Run this node"}
          </button>
          {active && run && (
            <button
              className="danger"
              onClick={() => void useRunStore.getState().cancel(run.id)}
              type="button"
            >
              Cancel
            </button>
          )}
          {retryable && run && (
            <button onClick={() => void retryRun(run.id)} type="button">
              Retry
            </button>
          )}
        </div>
      )}
      {offline && <p className="inspector-empty">{GENERATION_UNAVAILABLE}</p>}
      {relevantIssues.length > 0 && (
        <ul className="inspector-issues" role="alert">
          {relevantIssues.map((issue, index) => (
            <li key={`${issue.code}-${index}`}>
              <strong>{issue.code}</strong> {issue.message}
            </li>
          ))}
        </ul>
      )}
      {run && step && (
        <>
          <div className="inspector-row">
            <span>Status</span>
            <span className={`run-chip run-chip-${step.status}`}>
              {RUN_STATUS_LABEL[step.status]}
              {run.cancelRequested && active ? " · cancelling" : ""}
            </span>
          </div>
          {active && progress !== null && (
            <progress
              aria-label="How far this node's run has got"
              className="inspector-progress"
              max={1}
              value={progress}
            />
          )}
          <Row
            label="Started"
            value={formatTime(step.startedAt ?? run.createdAt)}
          />
          <Row label="Finished" value={formatTime(step.finishedAt)} />
          {failure && <p className="inspector-run-error">{failure}</p>}
          {!failure && run.error && !active && (
            <p className="inspector-run-error">{run.error}</p>
          )}
          {said ? (
            <p className="inspector-run-output">{said}</p>
          ) : (
            step.outputText && (
              <p className="inspector-run-output">{step.outputText}</p>
            )
          )}
        </>
      )}
      {asked.length > 1 && (
        <>
          <div className="inspector-row">
            <span>Asked in</span>
            <span className="inspector-run-list">
              {asked.map((entry) => (
                <span
                  className={`run-chip run-chip-${entry.step.status}`}
                  key={entry.run.id}
                >
                  {formatTime(entry.run.createdAt)} ·{" "}
                  {RUN_STATUS_LABEL[entry.step.status]}
                </span>
              ))}
            </span>
          </div>
          <p className="inspector-empty">
            Each ask went ahead. What the node shows is what the last of them to
            land wrote.
          </p>
        </>
      )}
      <LastGeneration canvas={canvas} node={node} />
      {slots.length > 0 && (
        <>
          <h3>Results</h3>
          {slots.map((slot, index) => (
            <div className="inspector-row" key={slot.id}>
              <span>{slot.isPrimary ? "Shown" : `Result ${index + 1}`}</span>
              <span className={`run-chip run-chip-${slot.status}`}>
                {slot.status}
              </span>
            </div>
          ))}
          {choices.length > 0 && (
            <div className="inspector-actions">
              {choices.map((choice) => (
                <button
                  key={choice.slotId}
                  onClick={() => chooseResult(node.id, choice.slotId)}
                  type="button"
                >
                  {choice.label}
                </button>
              ))}
            </div>
          )}
          {slots.find((slot) => slot.status === "failed")?.error && (
            <p className="inspector-run-error">
              {slots.find((slot) => slot.status === "failed")?.error}
            </p>
          )}
        </>
      )}
      {!run && executor !== null && relevantIssues.length === 0 && (
        <p className="inspector-empty">No runs yet</p>
      )}
    </section>
  );
}

function NodeInspector({
  canvas,
  node,
}: {
  canvas: CanvasDocument;
  node: WorkflowNode;
}) {
  return (
    <>
      <TitleField node={node} />
      <div className="inspector-row">
        <span>Kind</span>
        <span>{node.kind}</span>
      </div>
      <div className="inspector-row">
        <span>Position</span>
        <span>
          {Math.round(node.bounds.x)}, {Math.round(node.bounds.y)} ·{" "}
          {Math.round(node.bounds.width)}×{Math.round(node.bounds.height)}
        </span>
      </div>
      {node.kind === "text" && <TextSection node={node} />}
      {node.kind === "operation" && <OperationSection node={node} />}
      {node.kind === "export" && (
        <div className="inspector-row">
          <span>Format</span>
          <span>{(node.data as { format?: string }).format ?? ""}</span>
        </div>
      )}
      <GenerationSection node={node} />
      <MediaAssetSection node={node} />
      <InputChips canvas={canvas} node={node} />
      <RunSection canvas={canvas} node={node} />
    </>
  );
}

function TextSection({ node }: { node: WorkflowNode }) {
  const content = (node.data as { content?: string }).content ?? "";
  return (
    <section className="inspector-section">
      <h3>Content</h3>
      <p className="inspector-text-excerpt">
        {content.trim() ? content.slice(0, 280) : "Empty"}
      </p>
      <div className="inspector-actions">
        <button
          onClick={() => useEditorStore.getState().startEditingText(node.id)}
          type="button"
        >
          Edit text
        </button>
      </div>
    </section>
  );
}

function OperationSection({ node }: { node: WorkflowNode }) {
  const data = node.data as {
    operationType?: string;
    parameters?: Record<string, unknown>;
  };
  const params = Object.entries(data.parameters ?? {});
  return (
    <section className="inspector-section">
      <h3>Operation</h3>
      <Row label="Type" value={data.operationType ?? ""} />
      {params.map(([key, value]) => (
        <Row key={key} label={key} value={String(value)} />
      ))}
    </section>
  );
}

function EdgeInspector({
  canvas,
  edge,
}: {
  canvas: CanvasDocument;
  edge: WorkflowEdge;
}) {
  const endpoint = (nodeId: string, portId: string) => {
    const node = canvas.nodes.find((entry) => entry.id === nodeId);
    const port = node?.ports.find((entry) => entry.id === portId);
    return node ? `${node.title}${port ? ` · ${port.label}` : ""}` : "Unknown";
  };
  return (
    <>
      <h2 className="inspector-heading">Edge</h2>
      <Row
        label="From"
        value={endpoint(edge.source.nodeId, edge.source.portId)}
      />
      <Row
        label="To"
        value={endpoint(edge.target.nodeId, edge.target.portId)}
      />
      <div className="inspector-actions">
        <button
          className="danger"
          onClick={() => deleteSelection()}
          type="button"
        >
          Delete edge
        </button>
      </div>
    </>
  );
}

export function InspectorPanel() {
  const selection = useEditorStore((state) => state.selection);
  const activeCanvas = useActiveCanvas();

  const selectedNodes = activeCanvas
    ? activeCanvas.nodes.filter((node) => selection.nodeIds.includes(node.id))
    : [];
  const selectedEdges = activeCanvas
    ? activeCanvas.edges.filter((edge) => selection.edgeIds.includes(edge.id))
    : [];

  let body;
  if (
    activeCanvas &&
    selectedNodes.length === 1 &&
    selectedEdges.length === 0
  ) {
    body = <NodeInspector canvas={activeCanvas} node={selectedNodes[0]} />;
  } else if (
    activeCanvas &&
    selectedEdges.length === 1 &&
    selectedNodes.length === 0
  ) {
    body = <EdgeInspector canvas={activeCanvas} edge={selectedEdges[0]} />;
  } else if (selectedNodes.length === 0 && selectedEdges.length === 0) {
    body = <p className="inspector-empty">Nothing selected</p>;
  } else {
    body = (
      <ul className="inspector-list">
        {selectedNodes.map((node) => (
          <li key={node.id}>
            <strong>{node.title}</strong>
            <span>{node.kind}</span>
          </li>
        ))}
        {selectedEdges.map((edge) => (
          <li key={edge.id}>
            <strong>Edge</strong>
            <span>
              {edge.source.nodeId} → {edge.target.nodeId}
            </span>
          </li>
        ))}
      </ul>
    );
  }

  return (
    <aside aria-label="Inspector" className="editor-inspector">
      <h2>Inspector</h2>
      {body}
    </aside>
  );
}
