//! Built-in converter deployment.
//!
//! On startup, every built-in converter whose version is newer than the
//! version recorded in its deployed `model.json` is written out — the protocol
//! adapter script and the self-contained document that names it. A converter
//! the reader customised carries a version of its own, so it is left as it is
//! until a later built-in version overtakes what it says.
//!
//! Only the built-in converter directories are ever written. A converter the
//! reader added under a capability directory is not this module's to touch,
//! and an upgrade does not take it away.

use std::path::Path;

use super::adapter::set_converter_root;
use super::registry::{script_name_beside, ModelConfig};

/// A single built-in converter, embedded at compile time.
pub struct ScriptDef {
    pub capability: &'static str,
    pub id: &'static str,
    /// The `model.json` source, deployed verbatim.
    pub config: &'static str,
    /// The Lua source of the protocol adapter the document names.
    pub script: &'static str,
}

impl ScriptDef {
    /// The converter directory's location under the models root.
    pub fn subdir(&self) -> String {
        format!("{}/{}", self.capability, self.id)
    }

    /// The embedded `model.json`, parsed.
    ///
    /// A document that does not parse, or that does not name a script beside
    /// itself, is a fault in this build rather than in anything a reader can
    /// fix, so it is refused here rather than deployed.
    pub fn model(&self) -> Result<ModelConfig, std::io::Error> {
        let invalid = |reason: &str, id: &str| {
            std::io::Error::other(format!("built-in converter '{id}': {reason}"))
        };
        let config: ModelConfig = serde_json::from_str(self.config)
            .map_err(|e| invalid(&format!("model.json does not parse: {e}"), self.id))?;
        if !script_name_beside(&config.script) {
            return Err(invalid(
                &format!(
                    "script '{}' is not a filename beside model.json",
                    config.script
                ),
                self.id,
            ));
        }
        Ok(config)
    }
}

// The built-in converters, one per directory under `converter-scripts/models`.
//
// Generated by `build.rs` rather than listed here, so shipping a converter is
// adding its directory and nothing else. Each document carries the converter's
// own version, bumped when this build's copy of that converter changes.
include!(concat!(env!("OUT_DIR"), "/builtin_scripts.rs"));

/// The version a deployed `model.json` records, zero when it does not say or
/// cannot be read — either way a built-in of any version may take its place.
fn deployed_version(path: &Path) -> u32 {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|text| serde_json::from_str::<ModelConfig>(&text).ok())
        .map(|config| config.version)
        .unwrap_or(0)
}

/// Ensures every built-in converter is deployed to the models root, creating
/// or updating its directory and `model.json` as needed. Called once at
/// startup.
///
/// A converter whose deployed version is already at least the built-in
/// version is left untouched, so a converter the reader customised survives
/// until a later built-in version overtakes what it says. Directories this
/// build does not know are never read, written, or removed.
pub async fn ensure_deployed(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    for def in BUILTIN_SCRIPTS {
        // Each document is parsed before its own write, so a converter whose
        // embedded document does not parse deploys nothing at all. The
        // documents ship with the binary, so this is a build defect and the
        // tests that read every one of them are where it should be caught.
        let config = def.model()?;
        let dir = root.join(def.subdir());
        if deployed_version(&dir.join("model.json")) >= config.version {
            continue;
        }
        tokio::fs::create_dir_all(&dir).await?;
        tokio::fs::write(dir.join(&config.script), def.script).await?;
        tokio::fs::write(dir.join("model.json"), def.config).await?;
    }
    set_converter_root(root.to_path_buf());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::converter::registry::ConverterRegistry;

    async fn deploy(dir: &Path) {
        ensure_deployed(dir).await.unwrap();
    }

    /// Every embedded document parses, claims a version, and names the script
    /// embedded beside it. The script itself cannot be checked here — the
    /// adapter only runs it — so its emptiness is what a build defect would
    /// leave behind. The list is generated from the converter directories, so
    /// what these assertions protect is that each directory is a whole
    /// converter and that no two claim the same name.
    #[test]
    fn every_built_in_converter_is_well_formed_and_uniquely_named() {
        assert!(!BUILTIN_SCRIPTS.is_empty());
        let mut named: Vec<(&str, &str)> = Vec::new();
        for def in BUILTIN_SCRIPTS {
            let config = def.model().unwrap_or_else(|e| panic!("{e}"));
            assert!(config.version >= 1, "{}", def.id);
            assert!(!config.display_name.is_empty(), "{}", def.id);
            assert!(!config.url_example.is_empty(), "{}", def.id);
            assert!(!def.script.is_empty(), "{}", def.id);
            assert!(
                !named.contains(&(def.capability, def.id)),
                "{}/{} is declared twice",
                def.capability,
                def.id
            );
            named.push((def.capability, def.id));
        }
    }

    /// What the build embeds is what a deployment ends up holding: a converter
    /// that could not be deployed would be one the program claims to have and
    /// the registry never offers.
    #[tokio::test]
    async fn every_built_in_converter_reaches_the_registry_it_deploys_to() {
        let dir = tempfile::tempdir().unwrap();
        deploy(dir.path()).await;

        let registry = ConverterRegistry::load(dir.path());
        for def in BUILTIN_SCRIPTS {
            let entry = registry
                .find(def.id)
                .unwrap_or_else(|| panic!("{}/{} was not deployed", def.capability, def.id));
            assert_eq!(
                entry.script,
                format!(
                    "{}/{}/{}",
                    def.capability,
                    def.id,
                    def.model().unwrap().script
                )
            );
        }
    }

    #[tokio::test]
    async fn deploys_every_built_in_converter_under_its_capability() {
        let dir = tempfile::tempdir().unwrap();
        deploy(dir.path()).await;

        let registry = ConverterRegistry::load(dir.path());
        assert!(registry.find("openaiChat").is_some());
        assert!(registry.find("bailianAsr").is_some());
        assert!(registry.find("bailianMusic").is_some());
        assert_eq!(registry.protocols_for("asr").unwrap().len(), 1);
        // What the registry reports is what is on the disk: the document and
        // the script it names both sit in the converter's own directory.
        let entry = registry.find("bailianVideo").unwrap();
        let script = dir.path().join(&entry.script);
        assert!(script.is_file(), "{}", script.display());
        assert!(dir.path().join("video/bailianVideo/model.json").is_file());

        // A second deploy finds every document already at its version and
        // leaves the tree as it is.
        deploy(dir.path()).await;
        assert!(dir
            .path()
            .join("video/bailianVideo/bailian-video.lua")
            .is_file());
    }

    #[tokio::test]
    async fn a_reader_added_converter_survives_an_upgrade() {
        let dir = tempfile::tempdir().unwrap();
        deploy(dir.path()).await;

        // A converter of the reader's own: a directory beside the built-ins,
        // claiming no version.
        let custom = dir.path().join("text/myProtocol");
        std::fs::create_dir_all(&custom).unwrap();
        std::fs::write(custom.join("my-protocol.lua"), "-- mine").unwrap();
        std::fs::write(
            custom.join("model.json"),
            r#"{"displayName": "Mine", "urlExample": "https://mine.example.com", "script": "my-protocol.lua"}"#,
        )
        .unwrap();

        deploy(dir.path()).await;

        assert!(custom.join("model.json").is_file());
        assert!(custom.join("my-protocol.lua").is_file());
        let registry = ConverterRegistry::load(dir.path());
        assert!(registry.find("myProtocol").is_some());
    }

    #[tokio::test]
    async fn a_converter_keeps_its_document_until_a_later_version_overtakes_it() {
        let dir = tempfile::tempdir().unwrap();
        deploy(dir.path()).await;

        let document = dir.path().join("text/openaiChat/model.json");
        std::fs::write(
            &document,
            r#"{"displayName": "Mine", "urlExample": "https://mine.example.com", "script": "openai-chat.lua", "version": 99}"#,
        )
        .unwrap();
        deploy(dir.path()).await;

        let text = std::fs::read_to_string(&document).unwrap();
        assert!(text.contains("Mine"), "{text}");
    }

    #[tokio::test]
    async fn a_document_that_does_not_say_its_version_is_taken_over() {
        let dir = tempfile::tempdir().unwrap();
        deploy(dir.path()).await;

        let document = dir.path().join("text/gemini/model.json");
        std::fs::write(
            &document,
            r#"{"displayName": "Anonymous", "urlExample": "https://example.com", "script": "gemini.lua"}"#,
        )
        .unwrap();
        deploy(dir.path()).await;

        let text = std::fs::read_to_string(&document).unwrap();
        assert!(text.contains("Google Gemini"), "{text}");
    }
}
